/*
LICENCIA JOSE JAVIER BO
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
Lista de paquetes:
 */
package gui;

import dibujos.Dibujo;
import java.awt.Graphics;
import java.util.ArrayList;
import logica.Logica;

/**
 * Clase que hara de lienzo. En su método paintComponent (sobreescrito) se recoge
 * el array de dibujos a mostrar. Actualiza el valor de ancho y alto del lienzo
 * y los dibuja
 * @author Jose Javier Bailon Ortiz
 */
public class Lienzo extends javax.swing.JPanel {

    /**
     * Creates new form Lienzo
     */
    public Lienzo() {
        initComponents();
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        
        //recoger dimensiones del lienzo
        int ancho=this.getWidth();
        int alto=this.getHeight();
        //recoger dibujos
       ArrayList<Dibujo> dibujos = Logica.getDibujos();
       
       //iterar por los dibujos actualizando el valor de dimensiones del lienzo
        for (Dibujo dibujo : dibujos) {
            dibujo.setLienzoAncho(ancho);
            dibujo.setLienzoAlto(alto);
            //dibujar
            dibujo.dibujar(g);
        }
     }

   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
